version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: multi-container-app
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db-data:
